### ISSUE TITLE
Exapmple Issue #1 (please ignore)

### ISSUE THREAD

**Issue by janhendrikstruve** [janhendrikstruve/capstone-project#1]

**Comment by janhendrikstruve** [comment]
## Value proposition
**As a**...
**I need**....
**to be able to**...

## Description (text, scribbles, images, designs)

## Acceptance Criteria 
- [ ]  example: Alle inputs are `required`(browser shows warning if empty)
- [ ]  example: max. 100 Characters for a title
- [ ]  example: Amount has to be a Integer (no float Number)
- [ ]  example: The title and amount should never overlap

## Tasks

- [ ]  Form component
- [ ]  List component
- [ ]  Calory goal / Calories left component
- [ ]  Integrate components into App
- [ ]  Setup deployment
