### ISSUE TITLE
Implement local storage

### ISSUE THREAD

**Issue by janhendrikstruve** [janhendrikstruve/capstone-project#17]
## Value proposition
**As a** user
**I need** to save my Chords in the local storage of the browser
**to be able to** see them after restarting my browser or reloading the site

## Acceptance Criteria
- [x] Input and saved Chords should stay after reloading 

## Tasks
- [x] Create a stickyState hook that replaces the original state
- [x] Ckeck, if every input and the saved CHords stay after reloading
- [x] Ckeck, if every input and the saved CHords stay restarting
