### ISSUE TITLE
Chord folder

### ISSUE THREAD

**Issue by janhendrikstruve** [janhendrikstruve/capstone-project#2]
## Value proposition
**As a** user
**I need** a way to safe my chords in a separate folder
**to be able to** have a better overview

## Description (text, scribbles, images, designs)
![guitar-app-2](https://user-images.githubusercontent.com/91412287/142833207-f6b02097-fb01-429b-9844-e95fc81880de.png)

## Acceptance Criteria 
**Add page:**
- [ ] Chord folder should only be available, if at least one chord was saved (otherwise it should be greyed out)
- [ ] Chord folder should contain a list of all saved chords
- [ ] Chord folder should contain an add button, which redirects to the "Add chord" form

## Tasks

- [ ] Lift saved-chord state up in App.tsx
- [ ] Create folder button
- [ ] Let folder button redirect to folder page
- [ ] Create Separate folder page
- [ ] Create List of chords in folder page
- [ ] create "add" button in folder page
- [ ] Let "add" button redirect to to "save-chords" page
