### ISSUE TITLE
Fingerboard

### ISSUE THREAD

**Issue by janhendrikstruve** [janhendrikstruve/capstone-project#3]
## Value proposition
**As a** user
**I need** a digital version of a guitar fingerboard
**to be able to** quickly note down chords while playing

## Description (text, scribbles, images, designs)
![guitar-app-state1](https://user-images.githubusercontent.com/91412287/142860948-f0c5375f-405f-4a15-897e-282ee040ee83.png)

## Acceptance Criteria 
- [x] Every string on every fret should be clickable
- [x] It should be possible, to navigate up and down on the fingerboard, using the up and down buttons
- [x] The "fr" text field in the upper left corner should show, which Fret the top shown Fret is
- [x] The upper border of the fingerboard should be fat, to signal, that it's the upper end of the guitar

## Tasks
- [x] Create feature branch
- [x] Create Readme
- [x] Create Button component
- [x] Create Fret component
- [x] Create Fingerboard component
- [x] Create Dashboard Page
