### ISSUE TITLE
Save-Chords

### ISSUE THREAD

**Issue by janhendrikstruve** [janhendrikstruve/capstone-project#5]
## Value proposition
**As a** user
**I need** a way to safe my guitar chords
**to be able to** have a look at them, if i should ever forget how to grab them.

## Description (text, scribbles, images, designs)
![guitar-app-save-function](https://user-images.githubusercontent.com/91412287/142995052-13f48197-6f55-4403-9cb9-de3fda787e04.png)

## Acceptance Criteria 
**Add page:**
- [x] At least one string should be grabbed
- [x] Input field shouldn't be empty
- [x] Max. 100 Characters for a chord
- [x] Throw browser warning, these criteria are not fulfilled
- [x] Safe button should only be available, if strings are clicked and the chord name is filled (otherwise it should be greyed out)

## Out of Scope
- delete button for each guitar card

## Tasks
**Add page:**
- [x] Build input field component for the chord name
- [x] Build safe button component
      (Should show saved chord under input form,when clicked)
- [x] Program browser warning, if fingerboard or input field is empty
- [x] Prevent chord from being saved, if fingerboard or input field is empty
- [x] If fingerboard and input field is filled, save the chord and the chord name on the bottom of the page
