### ISSUE TITLE
Toggle-Chords

### ISSUE THREAD

**Issue by janhendrikstruve** [janhendrikstruve/capstone-project#9]
## Value proposition
**As a** user
**I need** to unselect my chords by pressing on the string again
**to be able to** correct my entry

## Description

![GuitarApp-toggle-chords](https://user-images.githubusercontent.com/91412287/144744262-7e60291b-00e7-40ae-aa49-2d12c48e829e.png)

## Acceptance Criteria 
- [ ] The selection of the string should toggle by pressing it
- [ ] Then selectin a new fret on the string, it should unselect the other one

## Tasks
- [ ] Enhance handleClick function, so it unselects the selected string, when pressing it again
